name: CMake CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    build-dir: ${{ runner.workspace }}/build
    # will set the CC & CXX for cmake
    cc: gcc
    cxx: g++
    build-type: Release
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && mkdir data && cd data && mkdir anim && ctest
