name: CMake CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S . -B build
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && mkdir data && cd data && mkdir anim && ctest
